import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {TopNavBar , NavBar , Landing, ShopNewArrivals, TrashTalk, BestSellingBags} from "../components/index"
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* LandingPage */}
        <Landing/>
        {/* Shop New Arrivals */}
        <ShopNewArrivals/>
        {/* Trash Talk */}
        <TrashTalk/>
        {/* Best selling bags */}
        <BestSellingBags/>
      </main>
    </>
  )
}
